#! /bin/sh
ssl_key_pass_path="$base_dir/var/ssl_key_pass"
ca_server_root_pass_path="$base_dir/var/ca_server_root_pass"
ca_server_intermediate_pass_path="$base_dir/var/ca_server_intermediate_pass"
ca_client_root_pass_path="$base_dir/var/ca_client_root_pass"
ca_client_intermediate_pass_path="$base_dir/var/ca_client_intermediate_pass"
server_key_pass_path="$base_dir/var/server_key_pass"
client_key_pass_path="$base_dir/var/client_key_pass"
cas_dir="$base_dir/cas"
ca_template_dir="$cas_dir/ca_template"
ca_server_root_dir="$cas_dir/server_root"
ca_server_intermediate_dir="$cas_dir/server_intermediate"
ca_client_root_dir="$cas_dir/client_root"
ca_client_intermediate_dir="$cas_dir/client_intermediate"
